[build-system]
requires = ["setuptools >= 30.3.0", "wheel"]

[project]
name = "Mopidy-Eboback"
version = "4.0.0"
description = "First version voor mopidy V4"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "Mopidy >= 4.0.0a1",
    "Pykka >= 3.1.1",
    "uritools >= 1.0",
    "mutagen >= 1.47",
    "jsons >= 1.6.3",
    "wavinfo >= 4.0.0",
    "pyalsaaudio >= 0.11.0",
    "ConfigUpdater >= 3.2",
]

[project.entry-points."mopidy.ext"]
eboback = "mopidy_eboback:Extension"

[tool.setuptools.packages.find]
include = ["mopidy_eboback*"]